# Generated by Django 4.2.7 on 2023-12-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_profile_is_accepted_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, choices=[(1, 'ASAP'), (2, 'Within a Week'), (3, 'A Month'), (4, 'Custom')], null=True)),
                ('currency', models.IntegerField(blank=True, choices=[(1, 'TZS'), (2, 'Dollar')], default=1, null=True)),
                ('payment_type', models.IntegerField(blank=True, choices=[(1, 'pay_by_hour'), (2, 'pay_fixed_price')], null=True)),
                ('budget', models.IntegerField(blank=True, choices=[(1, 'Basic(20,000Tsh - 50,000Tsh/hour)'), (2, 'Standard(30,000Tsh - 60,000Tsh/hour)'), (3, 'Custom')], null=True)),
                ('amount', models.CharField(blank=True, max_length=300, null=True)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
