# Generated by Django 4.2.7 on 2024-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experience_of_freelancer',
            field=models.IntegerField(blank=True, choices=[(0, '1 year'), (1, '2 years')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium')], null=True),
        ),
    ]
