# Generated by Django 4.2.7 on 2023-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_is_accepted_term_and_more'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='base.skill'),
        ),
    ]
