# Generated by Django 4.2.7 on 2024-03-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_project_experience_of_freelancer_project_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='experience_of_freelancer',
            new_name='experience',
        ),
    ]
