# Generated by Django 4.2.7 on 2023-12-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='backend.project'),
        ),
    ]
