# Generated by Django 4.2.7 on 2024-03-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_experience'),
        ('backend', '0003_rename_experience_of_freelancer_project_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.experience'),
        ),
    ]
