# Generated by Django 4.2.7 on 2024-04-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_project_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='proposal',
            new_name='message',
        ),
    ]
