# Generated by Django 4.2.7 on 2024-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_proposal_bid_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='proposal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
