# Generated by Django 4.2.7 on 2024-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_bid_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Pending'), (2, 'In Review'), (3, 'Approved'), (4, 'Rejected'), (5, 'On Going'), (6, 'Completed'), (7, 'Closed')], default=0, null=True),
        ),
    ]
