# Generated by Django 4.2.7 on 2024-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_project_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
