# Generated by Django 4.2.7 on 2024-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_duration_project_is_applied_alter_bid_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
