# Generated by Django 4.2.7 on 2024-01-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_project_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'In Review'), (3, 'Approved'), (4, 'Rejected')], default=1, null=True),
        ),
    ]
