# Generated by Django 4.2.7 on 2024-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_bid_attachment_bid_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='identity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
