# Generated by Django 4.2.7 on 2024-01-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
