# Generated by Django 4.2.7 on 2024-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_bid_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
