# Generated by Django 4.2.7 on 2024-01-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_profile_projectid'),
        ('backend', '0013_remove_bid_email_bid_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='base.category'),
        ),
    ]
