# Generated by Django 4.2.7 on 2023-12-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
