# Generated by Django 4.2.7 on 2024-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_access_token',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
