# Generated by Django 4.2.7 on 2023-12-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
