# Generated by Django 4.2.7 on 2023-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_accepted_term',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
