# Generated by Django 4.2.7 on 2024-01-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_projectid_profile_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projectId',
        ),
    ]
