# Generated by Django 4.2.7 on 2024-06-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_otp_is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
