# Generated by Django 4.2.7 on 2024-01-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_profile_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
