# Generated by Django 4.2.7 on 2024-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_password_otp_created_at'),
        ('base', '0009_profile_password_otp_created_at_alter_profile_rate'),
    ]

    operations = [
    ]
