# Generated by Django 4.2.7 on 2024-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_profile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
