# Generated by Django 4.2.7 on 2024-08-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20240805_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_otp_created_at',
        ),
    ]
