# Generated by Django 4.2.7 on 2024-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_profile_password_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_otp_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
