# Generated by Django 4.2.7 on 2024-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_otp_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow')], max_length=300, null=True),
        ),
    ]
