# Generated by Django 4.2.7 on 2024-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow')], default='blue', max_length=300, null=True),
        ),
    ]
